// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    KV: KVNamespace;
    BSKY_USERNAME: string;
    BSKY_PASSWORD: string;
    FEED_URL: string;
}
